//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountView2
    {
        public int ACC_ID { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_EN_NAME { get; set; }
        public byte ACC_TYPE_ID { get; set; }
        public System.DateTime ACC_DATE { get; set; }
        public System.DateTime ACC_CHECK_DATE { get; set; }
        public byte ACC_STATE { get; set; }
        public double ACC_CREDIT { get; set; }
        public double ACC_DEBIT { get; set; }
        public Nullable<double> ACC_MAX_DEBIT { get; set; }
        public short CURRENCY_ID { get; set; }
        public Nullable<int> PARENT_ACC_ID { get; set; }
        public Nullable<int> FINAL_ACC_ID { get; set; }
        public Nullable<int> ACC_LEVEL { get; set; }
        public string ACC_REMARKS { get; set; }
        public short ACC_NSONS { get; set; }
        public string ACC_TURNNING_YES_OR_NO { get; set; }
        public byte ACC_DEBIT_OR_CREDIT_OR_WITHOUT { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public Nullable<short> EMP_ID { get; set; }
        public Nullable<short> AREA_ID { get; set; }
        public Nullable<short> GOV_ID { get; set; }
        public Nullable<int> COM_BRN_ID { get; set; }
    }
}
