//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_DISCOUNT_ITEM
    {
        public int ACC_ITEM_DIS_ID { get; set; }
        public int ACC_ID { get; set; }
        public int ITEM_ID { get; set; }
        public double ITEM_ID_PURCHASES_DISCOUNT { get; set; }
        public double ITEM_ID_SALES_DISCOUNT { get; set; }
    }
}
