//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_DISCOUNT
    {
        public int ACC_DIS_ID { get; set; }
        public int ACC_ID { get; set; }
        public byte ACC_CUSTOMER_SUPPLIER { get; set; }
        public int GROUP_ID { get; set; }
        public byte GROUP_DISCOUNT { get; set; }
        public byte GROUP_DISCOUNT_PLUS { get; set; }
    }
}
