//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOWANCES_SANCTIONS
    {
        public short ALLOWANCES_SANCTIONS_ID { get; set; }
        public short ALLOWANCES_SANCTIONS_CODE { get; set; }
        public string ALLOWANCES_SANCTIONS_NAME { get; set; }
        public string TYPE { get; set; }
    }
}
