//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public short AREA_ID { get; set; }
        public string AREA_CODE { get; set; }
        public string AREA_AR_NAME { get; set; }
        public string AREA_EN_NAME { get; set; }
        public string AREA_REMARKS { get; set; }
    }
}
