//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORS_COPYRIGHT_DETAILS
    {
        public int COPYRIGHT_ID { get; set; }
        public int ACC_ID { get; set; }
        public short GRID_ROW_NUMBER { get; set; }
        public int ITEM_ID { get; set; }
        public double QTY_BEFORE { get; set; }
        public double QTY { get; set; }
        public double QTY_REALY { get; set; }
        public double QTY_PRINT { get; set; }
        public double MOVE_INVENTORY { get; set; }
        public double QTY_SALES_NET { get; set; }
        public double GIFTS { get; set; }
        public double PRICE { get; set; }
        public double TRADE_DIS { get; set; }
        public double COPYRIGHT { get; set; }
        public double COPYRIGHT_PUBLISHER { get; set; }
        public double COST { get; set; }
    }
}
