//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORS_COPYRIGHT_ADDITIONAL
    {
        public int COPYRIGHT_ID { get; set; }
        public short GRID_ROW_NUMBER { get; set; }
        public string ADDITIONAL_EXPLAIN { get; set; }
        public double ADDITIONAL_VALUE { get; set; }
    }
}
