//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORS_COPYRIGHT_MASTER
    {
        public int COPYRIGHT_ID { get; set; }
        public int COPYRIGHT_NUMBER { get; set; }
        public System.DateTime COPYRIGHT_DATE { get; set; }
        public int PAY_ACC_ID { get; set; }
        public byte CALC_METHOD { get; set; }
        public int ACC_ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public long ENTRY_ID { get; set; }
    }
}
