//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_MASTER_DELETED_VIEW
    {
        public long BILL_ID { get; set; }
        public short BILL_SETTING_ID { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public string BILL_NUMBER { get; set; }
        public string BILL_REMARKS { get; set; }
        public Nullable<double> BILL_TOTAL { get; set; }
        public Nullable<double> BILL_TOTAL_DISC { get; set; }
        public Nullable<double> BILL_TOTAL_EXTRA { get; set; }
        public Nullable<int> SHIFT_NUMBER { get; set; }
        public string SELL_TYPE_AR_NAME { get; set; }
        public string PAY_TYPE_AR_NAME { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string COM_STORE_AR_NAME { get; set; }
        public string TO_COM_STORE_AR_NAME { get; set; }
        public Nullable<double> BILL_ANOTHER_DISC { get; set; }
        public Nullable<double> BILL_TOTAL_DISC_NOTPAID { get; set; }
        public Nullable<double> BILL_TOTAL_OTHER_DISC { get; set; }
        public string EMP_AR_NAME { get; set; }
        public string ACTION { get; set; }
    }
}
