//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_MASTER_VIEW
    {
        public Nullable<long> BILL_ID { get; set; }
        public Nullable<short> BILL_SETTING_ID { get; set; }
        public Nullable<System.DateTime> BILL_DATE { get; set; }
        public string BILL_NUMBER { get; set; }
        public string CURRENCY_AR_NAME { get; set; }
        public string CURRENCY_EN_NAME { get; set; }
        public string COM_BRN_AR_NAME { get; set; }
        public string COM_BRN_EN_NAME { get; set; }
        public string COST_CENTER_CODE { get; set; }
        public string COST_CENTER_EN_NAME { get; set; }
        public string COST_CENTER_AR_NAME { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<short> CURRENCY_ID { get; set; }
        public Nullable<short> EMP_ID { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_AR_NAME { get; set; }
        public string EMP_EN_NAME { get; set; }
        public Nullable<byte> SELL_TYPE_ID { get; set; }
        public string SELL_TYPE_AR_NAME { get; set; }
        public string SELL_TYPE_EN_NAME { get; set; }
        public string BILL_REMARKS { get; set; }
        public Nullable<double> BILL_TOTAL { get; set; }
        public string BILL_PAY_WAY { get; set; }
        public Nullable<double> BILL_TOTAL_DISC { get; set; }
        public Nullable<double> BILL_TOTAL_EXTRA { get; set; }
        public Nullable<bool> BILL_IS_POST { get; set; }
        public string COM_BRN_CODE { get; set; }
        public Nullable<short> COST_CENTER_ID { get; set; }
        public Nullable<int> COM_BRN_ID { get; set; }
        public Nullable<short> TO_COM_STORE_ID { get; set; }
        public Nullable<short> COM_STORE_ID { get; set; }
        public Nullable<int> ITEM_ACC_ID { get; set; }
        public Nullable<int> CUST_ACC_ID { get; set; }
        public string ACC_BRN_AR_NAME { get; set; }
        public string ACC_BRN_EN_NAME { get; set; }
        public Nullable<int> SHIFT_NUMBER { get; set; }
        public string ENTRY_NUMBER { get; set; }
        public Nullable<long> ENTRY_ID { get; set; }
        public Nullable<double> BILL_WIEGHT { get; set; }
        public Nullable<double> BILL_PAIDED { get; set; }
        public Nullable<byte> Expr1 { get; set; }
        public Nullable<double> kest_value { get; set; }
        public string WORK_ORDER_NUMBER { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
        public string BILL_AR_NAME { get; set; }
        public string COUNTER_VALUE { get; set; }
        public string COM_STORE_AR_NAME { get; set; }
        public string COM_STORE_EN_NAME { get; set; }
        public string COM_STORE_CODE { get; set; }
        public string PAY_TYPE_AR_NAME { get; set; }
        public string PAY_TYPE_EN_NAME { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_EN_NAME { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public string TO_COM_STORE_CODE { get; set; }
        public string TO_COM_STORE_AR_NAME { get; set; }
        public Nullable<double> THE_RETURN_PERCENTAGE { get; set; }
        public Nullable<System.DateTime> THE_LAST_DATE_FOR_RETURN { get; set; }
        public Nullable<double> BILL_ANOTHER_DISC { get; set; }
        public Nullable<double> ACC_CREDIT { get; set; }
        public Nullable<double> ACC_DEBIT { get; set; }
        public Nullable<bool> IS_IT_RESERVATION { get; set; }
        public string UID { get; set; }
        public Nullable<double> BILLCURRENTPAIDEDVALUE { get; set; }
        public Nullable<double> BILLCURRENTREMAINVALUE { get; set; }
        public string BILL_SHOW_NAME { get; set; }
        public Nullable<int> PAY_ACC_ID { get; set; }
        public Nullable<double> CURRENCY_RATE { get; set; }
        public Nullable<byte> QTY { get; set; }
        public Nullable<byte> PRICE { get; set; }
        public Nullable<byte> RATE { get; set; }
        public string BILL_EN_NAME { get; set; }
        public string BILL_ABRV_AR { get; set; }
        public string BILL_ABRV_EN { get; set; }
        public string ACC_CODE { get; set; }
        public Nullable<double> BILL_COST { get; set; }
        public Nullable<double> BILL_PROFIT { get; set; }
        public Nullable<double> BILL_TOTAL_DISC_NOTPAID { get; set; }
        public Nullable<double> BILL_TOTAL_OTHER_DISC { get; set; }
        public Nullable<System.DateTime> THE_LAST_DATE_FOR_RESEVED { get; set; }
        public Nullable<bool> RESERVATION_OR_NOT { get; set; }
        public string FIRSTBILLMESSAGE { get; set; }
        public string SECONDBILLMESSAGE { get; set; }
        public string HEADERBILLMESSAGE { get; set; }
        public Nullable<double> EXTRA_VALUE_ADD { get; set; }
        public Nullable<double> EXTRA_VALUE_RATE { get; set; }
        public Nullable<long> MASTER_BILL_ID { get; set; }
        public string BRANCHE_NAME { get; set; }
        public Nullable<bool> DISABLE { get; set; }
        public string NUMBER_ENTRY { get; set; }
        public Nullable<bool> ADD14 { get; set; }
        public Nullable<bool> DIS05 { get; set; }
        public Nullable<bool> DIS2 { get; set; }
        public Nullable<bool> DIS65 { get; set; }
        public Nullable<bool> DIS20FROMADD14 { get; set; }
        public Nullable<bool> DIS7 { get; set; }
        public string CUST_PHONE { get; set; }
    }
}
