//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_DETAILS_TEMP_VIEW
    {
        public long DETAILS_ID { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public string ITEM_EN_NAME { get; set; }
        public Nullable<bool> EXPIRED_DATE { get; set; }
        public Nullable<bool> SERIAL_IN_INPUT { get; set; }
        public Nullable<bool> SERIAL_IN_OUTPUT { get; set; }
        public Nullable<bool> PRODUCTION_DATE { get; set; }
        public short GRID_ROW_NUMBER { get; set; }
        public double QTY { get; set; }
        public double UNIT_PRICE { get; set; }
        public string BILL_DETAILS_REMARKS { get; set; }
        public double GIFT { get; set; }
        public Nullable<System.DateTime> PRODUCTION_VALUE { get; set; }
        public Nullable<System.DateTime> EXPIRED_VALUE { get; set; }
        public double DISC_RATE { get; set; }
        public double DISC_VALUE { get; set; }
        public double EXTRA_RATE { get; set; }
        public double EXTRA_VALUE { get; set; }
        public string UNIT_AR_NAME { get; set; }
        public string UNIT_EN_NAME { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_AR_NAME { get; set; }
        public string EMP_EN_NAME { get; set; }
        public long BILL_ID { get; set; }
        public int ITEM_ID { get; set; }
        public short UNIT_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public Nullable<double> MIN_QTY { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
        public Nullable<double> WHOLE_PRICE { get; set; }
        public Nullable<double> HALF_WHOLE_PRICE { get; set; }
        public Nullable<double> EMP_PRICE { get; set; }
        public Nullable<double> EXPORT_PRICE { get; set; }
        public Nullable<double> RETAIL_PRICE { get; set; }
        public Nullable<double> CONSUMER_PRICE { get; set; }
        public Nullable<double> BILL_INVENTORY_VALUE { get; set; }
        public Nullable<double> LAST_BUY_PRICE { get; set; }
        public Nullable<double> DISC_RATE_NOTPAIED { get; set; }
        public Nullable<double> TAXES { get; set; }
        public string ITEM_MODEL { get; set; }
        public Nullable<double> UNIT_TRANS_RATE { get; set; }
        public string Unit_Master { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string GROUP_AR_NAME { get; set; }
        public Nullable<byte> ITEM_TYPE { get; set; }
        public string PART_NO { get; set; }
        public string UNIT_BARCODE { get; set; }
        public Nullable<bool> NON_TAX { get; set; }
    }
}
