//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_MASTER_DETAILS_DAILY
    {
        public Nullable<long> Expr1 { get; set; }
        public Nullable<short> BILL_SETTING_ID { get; set; }
        public Nullable<System.DateTime> BILL_DATE { get; set; }
        public string BILL_NUMBER { get; set; }
        public string CURRENCY_AR_NAME { get; set; }
        public string CURRENCY_EN_NAME { get; set; }
        public string COM_BRN_AR_NAME { get; set; }
        public string COM_BRN_EN_NAME { get; set; }
        public string COST_CENTER_CODE { get; set; }
        public string COST_CENTER_EN_NAME { get; set; }
        public string COST_CENTER_AR_NAME { get; set; }
        public string CURRENCY_CODE { get; set; }
        public Nullable<short> CURRENCY_ID { get; set; }
        public Nullable<short> EMP_ID { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public Nullable<byte> SELL_TYPE_ID { get; set; }
        public string SELL_TYPE_AR_NAME { get; set; }
        public string SELL_TYPE_EN_NAME { get; set; }
        public string BILL_REMARKS { get; set; }
        public Nullable<double> CURRENCY_RATE { get; set; }
        public Nullable<double> BILL_TOTAL { get; set; }
        public string BILL_PAY_WAY { get; set; }
        public Nullable<double> BILL_TOTAL_DISC { get; set; }
        public Nullable<double> BILL_TOTAL_EXTRA { get; set; }
        public Nullable<bool> BILL_IS_POST { get; set; }
        public string COM_BRN_CODE { get; set; }
        public Nullable<short> COST_CENTER_ID { get; set; }
        public Nullable<int> COM_BRN_ID { get; set; }
        public Nullable<short> TO_COM_STORE_ID { get; set; }
        public Nullable<short> COM_STORE_ID { get; set; }
        public Nullable<int> ITEM_ACC_ID { get; set; }
        public Nullable<int> CUST_ACC_ID { get; set; }
        public string ACC_BRN_AR_NAME { get; set; }
        public string ACC_BRN_EN_NAME { get; set; }
        public Nullable<int> SHIFT_NUMBER { get; set; }
        public string ENTRY_NUMBER { get; set; }
        public Nullable<long> ENTRY_ID { get; set; }
        public Nullable<double> BILL_WIEGHT { get; set; }
        public Nullable<double> BILL_PAIDED { get; set; }
        public Nullable<byte> Expr5 { get; set; }
        public Nullable<double> kest_value { get; set; }
        public string WORK_ORDER_NUMBER { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
        public string BILL_AR_NAME { get; set; }
        public string COUNTER_VALUE { get; set; }
        public string COM_STORE_AR_NAME { get; set; }
        public string COM_STORE_EN_NAME { get; set; }
        public string COM_STORE_CODE { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_EN_NAME { get; set; }
        public string PAY_TYPE_AR_NAME { get; set; }
        public string PAY_TYPE_EN_NAME { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public string ITEM_EN_NAME { get; set; }
        public Nullable<bool> EXPIRED_DATE { get; set; }
        public Nullable<bool> SERIAL_IN_INPUT { get; set; }
        public Nullable<bool> SERIAL_IN_OUTPUT { get; set; }
        public Nullable<bool> PRODUCTION_DATE { get; set; }
        public short GRID_ROW_NUMBER { get; set; }
        public double QTY { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
        public Nullable<double> MIN_QTY { get; set; }
        public string ITEM_CODE { get; set; }
        public Nullable<short> UNIT_ID { get; set; }
        public int ITEM_ID { get; set; }
        public long BILL_ID { get; set; }
        public string UNIT_EN_NAME { get; set; }
        public string UNIT_AR_NAME { get; set; }
        public Nullable<double> EXTRA_VALUE { get; set; }
        public Nullable<double> EXTRA_RATE { get; set; }
        public Nullable<double> DISC_VALUE { get; set; }
        public Nullable<double> DISC_RATE { get; set; }
        public Nullable<System.DateTime> EXPIRED_VALUE { get; set; }
        public Nullable<System.DateTime> PRODUCTION_VALUE { get; set; }
        public Nullable<double> GIFT { get; set; }
        public string BILL_DETAILS_REMARKS { get; set; }
        public string TO_COM_STORE_CODE { get; set; }
        public string TO_COM_STORE_AR_NAME { get; set; }
        public Nullable<double> THE_RETURN_PERCENTAGE { get; set; }
        public Nullable<System.DateTime> THE_LAST_DATE_FOR_RETURN { get; set; }
        public Nullable<double> BILL_ANOTHER_DISC { get; set; }
        public string UID { get; set; }
        public Nullable<double> WHOLE_PRICE { get; set; }
        public Nullable<double> HALF_WHOLE_PRICE { get; set; }
        public Nullable<double> EMP_PRICE { get; set; }
        public Nullable<double> EXPORT_PRICE { get; set; }
        public Nullable<double> RETAIL_PRICE { get; set; }
        public Nullable<double> CONSUMER_PRICE { get; set; }
        public Nullable<double> BILL_INVENTORY_VALUE { get; set; }
        public Nullable<double> LAST_BUY_PRICE { get; set; }
        public Nullable<byte> Expr6 { get; set; }
        public Nullable<byte> PRICE { get; set; }
        public Nullable<byte> RATE { get; set; }
    }
}
