//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_DETAILS_VIEW_SUM_QTY
    {
        public long BILL_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public string UNIT_AR_NAME { get; set; }
        public string QTY_Print { get; set; }
        public string Price_Print { get; set; }
        public string TOTAL_Print { get; set; }
    }
}
