//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARGE_COMPANY
    {
        public short CHARGE_ID { get; set; }
        public string CHARGE_CODE { get; set; }
        public string CHARGE_NAME { get; set; }
    }
}
