//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARGE_POLICY_VIEW
    {
        public int CHARGE_POLICY_ID { get; set; }
        public short CHARGE_ID { get; set; }
        public string CHARGE_NAME { get; set; }
        public bool OUTSIDE_ACC { get; set; }
        public string ACC_NAME { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string CHARGE_POLICY_NUMBER { get; set; }
        public string PACKAGE_COUNT { get; set; }
        public System.DateTime CHARGE_POLICY_DATE { get; set; }
    }
}
