//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_TYPE
    {
        public byte CHECK_ID { get; set; }
        public string CHECK_AR_NAME { get; set; }
        public string CHECK_EN_NAME { get; set; }
    }
}
