//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COST_CENTERS
    {
        public short COST_CENTER_ID { get; set; }
        public string COST_CENTER_CODE { get; set; }
        public string COST_CENTER_AR_NAME { get; set; }
        public string COST_CENTER_EN_NAME { get; set; }
        public Nullable<short> COST_CENTER_MASTER_ID { get; set; }
        public string COST_CENTER_REMARKS { get; set; }
    }
}
