//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_SON
    {
        public int CUSTOMER_SON_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_SON_NAME { get; set; }
        public System.DateTime CUSTOMER_BIRTHDATE { get; set; }
        public bool CUSTOMER_SON_SEX { get; set; }
        public int CUSTOMER_SON_ORDER { get; set; }
    }
}
