//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBranch
    {
        public int ACC_ID { get; set; }
        public string ACC_BRN_AR_NAME { get; set; }
        public string ACC_BRN_EN_NAME { get; set; }
        public short NATION_ID { get; set; }
        public short GOV_ID { get; set; }
        public string BRN_ADDR_REMARKS { get; set; }
        public string BRN_REMARKS { get; set; }
        public string NATION_AR_NAME { get; set; }
        public string NATION_EN_NAME { get; set; }
        public string GOV_AR_NAME { get; set; }
        public string GOV_EN_NAME { get; set; }
    }
}
