//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATABASE
    {
        public int DATABASE_ID { get; set; }
        public string DATABASE_AR_NAME { get; set; }
        public string DATABASE_EN_NAME { get; set; }
        public string DATABASE_DESCRIPTION_NAME { get; set; }
        public System.DateTime FIRST_PERIOD_DATE { get; set; }
        public int CURRENCY_ID { get; set; }
    }
}
