//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_CERTIFICATE
    {
        public byte EMP_CERTIFICATE_ID { get; set; }
        public byte EMP_CERTIFICATE_CODE { get; set; }
        public string EMP_CERTIFICATE_NAME { get; set; }
    }
}
