//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES_IN_OUT
    {
        public int ACC_ID { get; set; }
        public System.DateTime DATE_ONLY { get; set; }
        public System.DateTime DATE_IN { get; set; }
        public Nullable<System.DateTime> DATE_OUT { get; set; }
    }
}
