//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesROUTA
    {
        public string EMP_CODE { get; set; }
        public string EMP_AR_NAME { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public string ROUTA { get; set; }
        public int ACC_ID { get; set; }
        public short EMP_ID { get; set; }
    }
}
