//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES_EXTRA_DISCOUNT_PAYMENT_MASTER
    {
        public int PAY_ID { get; set; }
        public int ACC_ID { get; set; }
        public byte TYPE { get; set; }
        public System.DateTime PAY_DATE_MASTER { get; set; }
        public double PAY_MASTER_VALUE { get; set; }
        public string PAY_REASON { get; set; }
    }
}
