//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES_EXTRA_DISCOUNT_PAYMENT_DETAILS
    {
        public int PAY_ID { get; set; }
        public byte ENTRY_ROW_NUMBER { get; set; }
        public double PAY_VALUE { get; set; }
        public System.DateTime PAY_DATE { get; set; }
    }
}
