//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES_NEW_VIEW
    {
        public int ACC_ID { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_EN_NAME { get; set; }
        public string EMP_NATIONAL_ID { get; set; }
        public Nullable<int> PARENT_ACC_ID { get; set; }
        public byte EMP_TYPE_ID { get; set; }
        public Nullable<int> COM_BRN_ID { get; set; }
        public Nullable<short> DEPT_ID { get; set; }
        public string EMP_BARCODE { get; set; }
        public byte[] EMP_BARCODE_IMAGE { get; set; }
        public byte[] EMP_PHOTO { get; set; }
        public string EMP_REMARKS { get; set; }
        public short NATIONALITY_ID { get; set; }
        public short NATION_ID { get; set; }
        public short GOV_ID { get; set; }
        public Nullable<int> TOWN_ID { get; set; }
        public Nullable<long> VILLAGE_ID { get; set; }
        public string EMP_ADDR_REMARKS { get; set; }
        public string EMP_STATE { get; set; }
        public byte EMP_CERTIFICATE_ID { get; set; }
        public string CERTIFICATE_NAME { get; set; }
        public bool MALE { get; set; }
        public Nullable<byte> POSITION_OF_THE_ARMY { get; set; }
        public byte PERSONAL_STATEMENT { get; set; }
        public byte POSITION_OF_INSURANCE { get; set; }
        public string INSURANCE_NO { get; set; }
        public System.DateTime BIRTH_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public byte WORKING_HOURS { get; set; }
        public double BASIC_SALARY { get; set; }
        public double PLUS_SALARY { get; set; }
        public double OUT_OF_INSURANCE { get; set; }
        public double SALARY_BOND { get; set; }
        public byte VACATIONS_BALANCE { get; set; }
        public double VACATION_DAY_VALUE { get; set; }
        public Nullable<double> VACATION_DAY_VALUE_WITHOUT { get; set; }
        public Nullable<byte> DAYS_ID_VACATION1 { get; set; }
        public Nullable<byte> DAYS_ID_VACATION2 { get; set; }
        public Nullable<byte> DAYS_WORK { get; set; }
        public Nullable<byte> VACATION_LIST { get; set; }
        public Nullable<double> VACATION_VALUE { get; set; }
        public Nullable<byte> VACATION_LIST_WITHOUT { get; set; }
        public Nullable<double> VACATION_VALUE_WITHOUT { get; set; }
        public byte ALLOW_MINUTE_IN { get; set; }
        public byte ALLOW_MINUTE_OUT { get; set; }
        public byte START_EXTRA_VALUE_AFTER_MINUTE { get; set; }
    }
}
