//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class entry
    {
        public string ENTRY_SETTING_AR_NAME { get; set; }
        public string ENTRY_NUMBER { get; set; }
        public Nullable<long> ENTRY_ID { get; set; }
        public Nullable<short> ENTRY_SETTING_ID { get; set; }
    }
}
