//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRY_GRID_COLUMNS
    {
        public short ENTRY_SETTING_ID { get; set; }
        public byte CREDIT_INDEX { get; set; }
        public short CREDIT_WIDTH { get; set; }
        public int CREDIT_COLOR { get; set; }
        public byte DEBIT_INDEX { get; set; }
        public short DEBIT_WIDTH { get; set; }
        public int DEBIT_COLOR { get; set; }
        public byte ACC_INDEX { get; set; }
        public short ACC_WIDTH { get; set; }
        public int ACC_COLOR { get; set; }
        public byte COST_CENTER_INDEX { get; set; }
        public short COST_CENTER_WIDTH { get; set; }
        public int COST_CENTER_COLOR { get; set; }
        public byte REMARKS_INDEX { get; set; }
        public short REMARKS_WIDTH { get; set; }
        public int REMARKS_COLOR { get; set; }
    }
}
