//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRY_SETTINGS
    {
        public short ENTRY_SETTING_ID { get; set; }
        public string ENTRY_SETTING_AR_NAME { get; set; }
        public string ENTRY_SETTING_EN_NAME { get; set; }
        public string ENTRY_SETTING_AR_ABRV { get; set; }
        public string ENTRY_SETTING_EN_ABRV { get; set; }
        public Nullable<int> ENTRY_ACC_ID { get; set; }
        public short CURRENCY_ID { get; set; }
        public bool AUTO_POSTING { get; set; }
        public byte ENTRY_TYPE_ID { get; set; }
        public bool ACCEPT_DIST_ACC { get; set; }
        public Nullable<bool> COSTCENTER_BELONG { get; set; }
        public bool PRINT_AS_RESET { get; set; }
        public bool SHOW_THE_LAST_BALANCE { get; set; }
        public byte NUMBEROFCOPIES { get; set; }
    }
}
