//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRY_DETAILS
    {
        public long ENTRY_ID { get; set; }
        public short ENTRY_ROW_NUMBER { get; set; }
        public int ACC_ID { get; set; }
        public double ENTRY_CREDIT { get; set; }
        public double ENTRY_DEBIT { get; set; }
        public string ENTRY_DETAILS_REMARKS { get; set; }
        public Nullable<short> COST_CENTER_ID { get; set; }
    }
}
