//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GET_BILL_INFO_supp
    {
        public Nullable<double> BILL_PAIDED { get; set; }
        public Nullable<double> BILL_TOTAL { get; set; }
        public Nullable<double> BILL_TOTAL_DISC { get; set; }
        public Nullable<double> BILL_TOTAL_EXTRA { get; set; }
        public long BILL_ID { get; set; }
        public string BILL_NUMBER { get; set; }
    }
}
