//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_DIS_ACCOUNT
    {
        public int ACC_DIS_ID { get; set; }
        public Nullable<int> ACC_ID { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string GROUP_CODE { get; set; }
        public string GROUP_AR_NAME { get; set; }
        public byte GROUP_DISCOUNT { get; set; }
        public byte GROUP_DISCOUNT_PLUS { get; set; }
        public byte ACC_CUSTOMER_SUPPLIER { get; set; }
    }
}
