//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_MOTION_VIEW
    {
        public long BILL_ID { get; set; }
        public short BILL_SETTING_ID { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public string BILL_NUMBER { get; set; }
        public string BILL_REMARKS { get; set; }
        public Nullable<double> BILL_TOTAL_DISC { get; set; }
        public string BILL_PAY_WAY { get; set; }
        public Nullable<double> BILL_TOTAL { get; set; }
        public Nullable<double> BILL_TOTAL_EXTRA { get; set; }
        public bool BILL_IS_POST { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
        public string COM_STORE_CODE { get; set; }
        public string COM_STORE_AR_NAME { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_AR_NAME { get; set; }
        public string EMP_EN_NAME { get; set; }
        public string COM_STORE_EN_NAME { get; set; }
        public string BILL_ABRV_AR { get; set; }
        public string BILL_ABRV_EN { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_EN_NAME { get; set; }
        public Nullable<int> CUST_ACC_ID { get; set; }
        public Nullable<short> COST_CENTER_ID { get; set; }
        public Nullable<short> COM_STORE_ID { get; set; }
        public Nullable<short> EMP_ID { get; set; }
        public string BILL_AR_NAME { get; set; }
        public string BILL_EN_NAME { get; set; }
        public Nullable<double> BILL_PAIDED { get; set; }
        public Nullable<long> Expr1 { get; set; }
        public string Expr2 { get; set; }
        public Nullable<long> cust_account_id { get; set; }
        public Nullable<double> kest_value { get; set; }
        public Nullable<int> SHIFT_NUMBER { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public Nullable<byte> SELL_TYPE_ID { get; set; }
        public Nullable<bool> IS_IT_RESERVATION { get; set; }
        public Nullable<long> ENTRY_ID { get; set; }
        public string UID { get; set; }
        public string Bill_Box { get; set; }
    }
}
