//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_COLLECT_WITH_PRICE
    {
        public string ITEM_CODE { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public Nullable<double> Expr2 { get; set; }
        public Nullable<double> Expr3 { get; set; }
        public Nullable<double> Expr4 { get; set; }
        public Nullable<double> Expr5 { get; set; }
        public Nullable<double> Expr6 { get; set; }
        public Nullable<double> Expr7 { get; set; }
    }
}
