//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_SERIALS
    {
        public int ITEM_ID { get; set; }
        public string ITEM_SERIAL { get; set; }
        public Nullable<long> PURCHASE_BILL_ID { get; set; }
        public Nullable<long> SELL_BILL_ID { get; set; }
        public Nullable<long> PURCHASE_BACK_BILL_ID { get; set; }
        public Nullable<long> SELL_BACK_BILL_ID { get; set; }
        public Nullable<long> SEND_BILL_ID { get; set; }
        public Nullable<long> RECIEV_BILL_ID { get; set; }
        public Nullable<long> TRANSFER_BILL_ID { get; set; }
        public Nullable<int> FROM_STORE_ID { get; set; }
        public Nullable<int> TO_STORE_ID { get; set; }
    }
}
