//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_INVENTORY_QTY_VIEW
    {
        public int ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public double QTY { get; set; }
        public Nullable<double> WHOLE_PRICE { get; set; }
        public Nullable<double> HALF_WHOLE_PRICE { get; set; }
        public Nullable<double> EMP_PRICE { get; set; }
        public Nullable<double> EXPORT_PRICE { get; set; }
        public Nullable<double> RETAIL_PRICE { get; set; }
        public Nullable<double> CONSUMER_PRICE { get; set; }
        public Nullable<double> LAST_BUY_PRICE { get; set; }
        public Nullable<double> WHOLE_PRICEQTY { get; set; }
        public Nullable<double> HALF_WHOLE_PRICEQTY { get; set; }
        public Nullable<double> EMP_PRICEQTY { get; set; }
        public Nullable<double> EXPORT_PRICEQTY { get; set; }
        public Nullable<double> RETAIL_PRICEQTY { get; set; }
        public Nullable<double> CONSUMER_PRICEQTY { get; set; }
        public Nullable<double> LAST_BUY_PRICEQTY { get; set; }
        public Nullable<double> AVG_PRICEQTY { get; set; }
        public string QTY_INPUT { get; set; }
        public string QTY_OUTPUT { get; set; }
        public short COM_STORE_ID { get; set; }
        public int GROUP_ID { get; set; }
        public string GROUP_AR_NAME { get; set; }
        public Nullable<int> ACC_ID { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string UNIT_AR_NAME { get; set; }
    }
}
