//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_DEFAULT_UNIT
    {
        public int ITEM_ID { get; set; }
        public double DEFAULT_UNIT_TRANS_RATE { get; set; }
        public string DEFAULT_UNIT_AR_NAME { get; set; }
        public Nullable<double> DEFAULT_WHOLE_PRICE { get; set; }
        public Nullable<double> DEFAULT_HALF_WHOLE_PRICE { get; set; }
        public Nullable<double> DEFAULT_EMP_PRICE { get; set; }
        public Nullable<double> DEFAULT_EXPORT_PRICE { get; set; }
        public Nullable<double> DEFAULT_RETAIL_PRICE { get; set; }
        public Nullable<double> DEFAULT_CONSUMER_PRICE { get; set; }
        public Nullable<double> DEFAULT_LAST_BUY_PRICE { get; set; }
    }
}
