//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_DIS_ACCOUNT
    {
        public int ACC_ITEM_DIS_ID { get; set; }
        public Nullable<int> ACC_ID { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public double ITEM_ID_PURCHASES_DISCOUNT { get; set; }
        public double ITEM_ID_SALES_DISCOUNT { get; set; }
    }
}
