//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_SHELIF_VIEW
    {
        public string ITEM_CODE { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public string UNIT_AR_NAME { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public string Expr2 { get; set; }
        public Nullable<double> WHOLE_PRICE { get; set; }
    }
}
