//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_QTY_VIEW
    {
        public int ITEM_ID { get; set; }
        public short COM_STORE_ID { get; set; }
        public double STORE_ITEM_QTY { get; set; }
        public Nullable<System.DateTime> ITEM_EXPIRE_DATE { get; set; }
        public string ITEM_CODE { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public string ITEM_EN_NAME { get; set; }
        public string GROUP_CODE { get; set; }
        public string GROUP_AR_NAME { get; set; }
        public string GROUP_EN_NAME { get; set; }
        public Nullable<double> MIN_QTY { get; set; }
        public string COM_STORE_CODE { get; set; }
        public string COM_STORE_AR_NAME { get; set; }
        public string COM_STORE_EN_NAME { get; set; }
    }
}
