//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_COMPANY_ID
    {
        public int ITEMS_COMPANY { get; set; }
        public int ITEM_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public Nullable<byte> TRADE_DIS { get; set; }
        public Nullable<byte> COPYRIGHT { get; set; }
        public Nullable<byte> COPYRIGHT_PUBLISHER { get; set; }
        public Nullable<bool> CO_IS_DEFAULT { get; set; }
    }
}
