//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_COST
    {
        public long BILL_ID { get; set; }
        public int ITEM_ID { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
        public double QTY { get; set; }
        public double UNIT_TRANS_RATE { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<double> YY { get; set; }
    }
}
