//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_QTY_OLD
    {
        public short BILL_SETTING { get; set; }
        public int ITEM_ID { get; set; }
        public int CUST_ACC_ID { get; set; }
        public System.DateTime DATE_DAY { get; set; }
        public double QTY_TOTAL { get; set; }
        public double PRICE { get; set; }
        public short STORE_ID { get; set; }
        public Nullable<short> TO_STORE_ID { get; set; }
        public byte BILL_EFFECT { get; set; }
    }
}
