//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_MEASURING
    {
        public int ITEM_ID { get; set; }
        public byte GRID_ROW_NUMBER { get; set; }
        public string CLASS_EN_NAME { get; set; }
        public double AMOUNT_MEASURING { get; set; }
    }
}
