//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOADBILL_NUMBERS_supp
    {
        public string BILL_NUMBER { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public Nullable<int> CUST_ACC_ID { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
        public string ACC_CODE { get; set; }
    }
}
