//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class load_kests_data_supp
    {
        public Nullable<double> kest_value { get; set; }
        public Nullable<long> kest_id { get; set; }
        public string kest_code { get; set; }
        public string bill_number { get; set; }
        public long bill_id { get; set; }
        public Nullable<System.DateTime> kest_date { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> cust_account_id { get; set; }
        public Nullable<byte> ACC_TYPE_ID { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_CODE { get; set; }
    }
}
