//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLD_PRICE_WITH_DATE
    {
        public int BILL_ID { get; set; }
        public byte BILL_TYPE { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public int ACC_ID { get; set; }
        public int ITEM_ID { get; set; }
        public double UNIT_PRICE { get; set; }
    }
}
