//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNEL_LATES
    {
        public byte LATE_ID { get; set; }
        public byte LATE_START_HOURS { get; set; }
        public byte LATE_START_MINUTE { get; set; }
        public byte LATE_START_PERIOD { get; set; }
        public byte LATE_TO_HOURS { get; set; }
        public byte LATE_TO_MINUTE { get; set; }
        public byte LATE_TO_PERIOD { get; set; }
        public byte DIS_HOURS { get; set; }
        public byte DIS_VALUE { get; set; }
    }
}
