//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNEL_OPTIONS
    {
        public byte DAYS_ID { get; set; }
        public byte START_DATE_HOURE { get; set; }
        public byte START_DATE_MINUTE { get; set; }
        public byte START_DATE_PERIOD { get; set; }
    }
}
