//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLICY_PRICES
    {
        public int POLICE_PRICE_ID { get; set; }
        public int GROUP_ID { get; set; }
        public byte DEFAULT_SELL_TYPE_ID { get; set; }
        public byte SELL_TYPE_ID1 { get; set; }
        public byte TYPE1 { get; set; }
        public double IN_DE_PRICES1 { get; set; }
        public byte SELL_TYPE_ID2 { get; set; }
        public byte TYPE2 { get; set; }
        public double IN_DE_PRICES2 { get; set; }
        public byte SELL_TYPE_ID3 { get; set; }
        public byte TYPE3 { get; set; }
        public double IN_DE_PRICES3 { get; set; }
        public byte SELL_TYPE_ID4 { get; set; }
        public byte TYPE4 { get; set; }
        public double IN_DE_PRICES4 { get; set; }
        public byte SELL_TYPE_ID5 { get; set; }
        public byte TYPE5 { get; set; }
        public double IN_DE_PRICES5 { get; set; }
        public byte SELL_TYPE_ID6 { get; set; }
        public byte TYPE6 { get; set; }
        public double IN_DE_PRICES6 { get; set; }
        public byte SELL_TYPE_ID7 { get; set; }
        public byte TYPE7 { get; set; }
        public double IN_DE_PRICES7 { get; set; }
    }
}
