//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINT_BARCODEBILLS
    {
        public long BILL_ID { get; set; }
        public int ITEM_ID { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public Nullable<short> UNIT_ID { get; set; }
        public string UNIT_AR_NAME { get; set; }
        public string UNIT_BARCODE { get; set; }
        public double QTY { get; set; }
        public Nullable<int> ITEM_UNIT_ID { get; set; }
    }
}
