//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_BILLS_CUSTOMERS_VIEW
    {
        public long BILL_ID { get; set; }
        public Nullable<int> CUST_ACC_ID { get; set; }
        public Nullable<double> BILL_TOTAL { get; set; }
        public Nullable<double> BILL_TOTAL_DISC { get; set; }
        public Nullable<double> BILL_TOTAL_EXTRA { get; set; }
        public Nullable<short> COST_CENTER_ID { get; set; }
        public Nullable<short> COM_STORE_ID { get; set; }
        public bool BILL_IS_POST { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_EN_NAME { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public Nullable<double> BILL_TOTAL_DISC_NOTPAID { get; set; }
    }
}
