//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_ACCOUNT_MOTION_VIEW
    {
        public long ENTRY_ID { get; set; }
        public string ENTRY_NUMBER { get; set; }
        public string ENTRY_SETTING_AR_NAME { get; set; }
        public string ENTRY_SETTING_EN_NAME { get; set; }
        public string ENTRY_SETTING_AR_ABRV { get; set; }
        public string ENTRY_SETTING_EN_ABRV { get; set; }
        public Nullable<byte> ENTRY_TYPE_ID { get; set; }
        public bool IS_POSTED { get; set; }
        public short ENTRY_SETTING_ID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public Nullable<int> ACC_ID { get; set; }
        public Nullable<short> ENTRY_ROW_NUMBER { get; set; }
        public Nullable<double> ENTRY_DEBIT { get; set; }
        public Nullable<double> ENTRY_CREDIT { get; set; }
        public string ENTRY_DETAILS_REMARKS { get; set; }
        public Nullable<short> COST_CENTER_ID { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_EN_NAME { get; set; }
        public string COST_CENTER_CODE { get; set; }
        public string COST_CENTER_AR_NAME { get; set; }
        public string COST_CENTER_EN_NAME { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public double CURRENCY_RATE { get; set; }
        public string ACC_CUSTOMER_CODE2 { get; set; }
        public string ACC_AR_NAME2 { get; set; }
        public string CHECK_NUMBER { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public Nullable<bool> PAIED { get; set; }
        public Nullable<byte> CHECK_ID { get; set; }
        public string ACC_AR_NAME3 { get; set; }
        public Nullable<byte> ACC_STATE { get; set; }
        public short CURRENCY_ID { get; set; }
    }
}
