//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_RESERVATION
    {
        public long BILL_ID { get; set; }
        public short BILL_SETTING_ID { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public string BILL_NUMBER { get; set; }
        public Nullable<System.DateTime> THE_LAST_DATE_FOR_RESEVED { get; set; }
        public Nullable<bool> RESERVATION_OR_NOT { get; set; }
        public string BILL_ABRV_AR { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public string BILL_AR_NAME { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
    }
}
