//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_ITEM_MOTION_VIEW
    {
        public long BILL_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public string ITEM_EN_NAME { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public Nullable<double> GIFT { get; set; }
        public string UNIT_AR_NAME { get; set; }
        public string UNIT_CODE { get; set; }
        public string UNIT_EN_NAME { get; set; }
        public string EMP_CODE { get; set; }
        public string EMP_AR_NAME { get; set; }
        public string EMP_EN_NAME { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public string BILL_NUMBER { get; set; }
        public string BILL_AR_NAME { get; set; }
        public string BILL_EN_NAME { get; set; }
        public string BILL_ABRV_AR { get; set; }
        public string BILL_ABRV_EN { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
        public Nullable<double> UNIT_TRANS_RATE { get; set; }
        public short BILL_SETTING_ID { get; set; }
        public string BILL_REMARKS { get; set; }
        public Nullable<double> EXTRA_VALUE { get; set; }
        public Nullable<double> EXTRA_RATE { get; set; }
        public Nullable<double> DISC_VALUE { get; set; }
        public Nullable<double> DISC_RATE { get; set; }
        public string COM_STORE_CODE { get; set; }
        public string COM_STORE_AR_NAME { get; set; }
        public string COM_STORE_EN_NAME { get; set; }
        public Nullable<short> COM_STORE_ID { get; set; }
        public Nullable<short> COST_CENTER_ID { get; set; }
        public Nullable<short> EMP_ID { get; set; }
        public Nullable<double> BILL_TOTAL_EXTRA { get; set; }
        public Nullable<double> BILL_TOTAL_DISC { get; set; }
        public string BILL_PAY_WAY { get; set; }
        public Nullable<double> BILL_TOTAL { get; set; }
        public Nullable<int> CUST_ACC_ID { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_EN_NAME { get; set; }
        public bool BILL_IS_POST { get; set; }
        public Nullable<short> GRID_ROW_NUMBER { get; set; }
        public Nullable<short> TO_COM_STORE_ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public Nullable<short> UNIT_ID { get; set; }
        public Nullable<double> BILL_COST { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public Nullable<byte> BILL_EFF_ID { get; set; }
    }
}
