//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEARCH_ENTRY_VIEW
    {
        public long ENTRY_ID { get; set; }
        public short ENTRY_SETTING_ID { get; set; }
        public string ENTRY_NUMBER { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public Nullable<double> ENTRY_VALUE { get; set; }
    }
}
