//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_GROUP
    {
        public int S_GROUP_ID { get; set; }
        public int S_GROUP_CODE { get; set; }
        public string S_GROUP_NAME { get; set; }
        public Nullable<int> S_GROUP_MASTER_ID { get; set; }
        public string S_GROUP_REMARKS { get; set; }
    }
}
