//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_BILL_MASTER
    {
        public int S_BILL_ID { get; set; }
        public string S_BILL_NUMBER { get; set; }
        public Nullable<double> S_BILL_TOTAL { get; set; }
        public Nullable<double> S_BILL_DISC { get; set; }
        public Nullable<double> S_BILL_EXTRA { get; set; }
        public Nullable<System.DateTime> S_BILL_DATE { get; set; }
        public Nullable<short> CURRENCY_ID { get; set; }
        public string S_BILL_REMARKS { get; set; }
    }
}
