//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_BILL_DETAILS_VIEW
    {
        public int S_BILL_ID { get; set; }
        public int SERVICE_ID { get; set; }
        public Nullable<double> S_QTY { get; set; }
        public Nullable<double> S_PRICE { get; set; }
        public Nullable<double> S_DISC { get; set; }
        public Nullable<double> S_EXTRA { get; set; }
        public Nullable<double> S_DISC_RATE { get; set; }
        public Nullable<double> S_EXTRA_RATE { get; set; }
        public string SERVICE_CODE { get; set; }
        public string SERVICE_NAME { get; set; }
        public string S_BILL_NUMBER { get; set; }
        public Nullable<System.DateTime> S_BILL_DATE { get; set; }
        public Nullable<double> SERVICE_COST { get; set; }
    }
}
