//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHORTCUT_VIEW
    {
        public string ORDER_AR_NAME { get; set; }
        public string ORDER_EN_NAME { get; set; }
        public short ORDER_ID { get; set; }
        public string KEY_TYPE { get; set; }
    }
}
