//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLD_ITEMS
    {
        public long BILL_ID { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public Nullable<short> COM_STORE_ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public string ITEM_AR_NAME { get; set; }
        public string BILL_PAY_WAY { get; set; }
        public Nullable<double> QTY { get; set; }
        public string ITEM_CODE { get; set; }
        public string UNIT_AR_NAME { get; set; }
        public string UNIT_CODE { get; set; }
        public Nullable<short> UNIT_ID { get; set; }
        public string ITEM_EN_NAME { get; set; }
        public Nullable<double> BillItemTotal { get; set; }
        public Nullable<double> DISC_RATE { get; set; }
        public Nullable<double> DISC_VALUE { get; set; }
        public Nullable<double> EXTRA_RATE { get; set; }
        public Nullable<double> EXTRA_VALUE { get; set; }
        public Nullable<double> LAST_BUY_PRICE { get; set; }
        public Nullable<int> CUST_ACC_ID { get; set; }
        public string GROUP_CODE { get; set; }
        public string GROUP_AR_NAME { get; set; }
        public Nullable<int> ACC_ID { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
    }
}
