//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_ITEMS
    {
        public int STORE_ITEM_ID { get; set; }
        public int ITEM_ID { get; set; }
        public short COM_STORE_ID { get; set; }
        public double STORE_ITEM_QTY { get; set; }
        public Nullable<System.DateTime> ITEM_EXPIRE_DATE { get; set; }
    }
}
