//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_DETAILS
    {
        public int ACC_ID { get; set; }
        public double YearContract { get; set; }
        public double Barcode { get; set; }
        public double NewBarcode { get; set; }
        public double DisBill { get; set; }
        public double DisMonth { get; set; }
        public double DisQuarter { get; set; }
        public double DisYear { get; set; }
        public double RentMonth { get; set; }
        public double RentGandol { get; set; }
        public double Branch { get; set; }
        public double Magazine { get; set; }
        public double ForCredit { get; set; }
    }
}
