//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_OPTIONS
    {
        public string UID { get; set; }
        public bool END_SYSTEM { get; set; }
        public bool ON_UPDATE { get; set; }
        public bool ON_SAVE { get; set; }
        public bool ON_DELETE { get; set; }
        public bool DATE_AFTER { get; set; }
        public bool SAME_ITEM_ON_BILL { get; set; }
        public bool SAME_ACC_ON_ENTRY { get; set; }
        public bool ON_POST_ENTRY { get; set; }
        public bool ON_POST_STORE { get; set; }
        public bool ON_POST_ACC { get; set; }
        public System.DateTime FIRST_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public System.DateTime OPERATION_DATE { get; set; }
        public Nullable<int> DEFAULT_CURRENCY { get; set; }
        public Nullable<byte> QTY { get; set; }
        public Nullable<byte> PRICE { get; set; }
        public Nullable<byte> RATE { get; set; }
        public string PRINTER_ID { get; set; }
        public bool ITEM_CODE { get; set; }
        public bool BILL_CODE { get; set; }
        public bool SERVICE_CODE { get; set; }
        public bool ITEM_GROUP_CODE { get; set; }
        public bool SERVICE_GROUP_CODE { get; set; }
        public bool ENTRY_CODE { get; set; }
        public bool ON_ASK_ABOUT_CHANGE { get; set; }
        public string HOW_MANY_BILL_CAN_NAVIGATE { get; set; }
        public Nullable<bool> SUPPLIER_ITEM_CODE { get; set; }
        public Nullable<bool> CAN_SEE_THE_PRICE { get; set; }
        public Nullable<bool> UNPOSTED_BILL { get; set; }
        public Nullable<bool> GENERATE_THE_CURRENCY_DIFFERENCE_ENTRY_FOR_ENTRIES { get; set; }
        public Nullable<bool> GENERATE_THE_CURRENCY_DIFFERENCE_ENTRY_FOR_BILLS { get; set; }
        public Nullable<int> CURRENCYDIFFERENCEACCOUNTID { get; set; }
        public string LOSTACCOUNTID { get; set; }
        public Nullable<bool> CAN_CHANGE_BILL_DATE { get; set; }
        public Nullable<bool> CAN_SEE_THE_BILL_PROFIT { get; set; }
        public Nullable<bool> CAN_SEE_THE_CURRENT_QTY_ON_BILL { get; set; }
        public Nullable<bool> CAN_CHANGE_THE_PRICE_ON_THE_BILL { get; set; }
        public Nullable<bool> CAN_SEE_THE_CHEQUES_NOTIFICATIONS { get; set; }
        public string NUMBEROFDAYSBEFOREDUEDATE { get; set; }
        public Nullable<bool> LOAD_THE_LAST_BILLS_AFTER_SAVE { get; set; }
        public Nullable<bool> ISITORDEREDBYITEMCODEORNOT { get; set; }
        public Nullable<bool> CAN_CHANGE_BILL_DISACOUNT { get; set; }
        public Nullable<bool> CAN_SEE_HIS_BILL { get; set; }
        public Nullable<bool> CAN_CHANGE_TYPE_PRICE { get; set; }
        public Nullable<bool> CAN_CHANGE_BILL_ACCOUNT { get; set; }
        public Nullable<bool> CAN_CHANGE_THE_PRICE_TO_LESS_SALES { get; set; }
        public Nullable<bool> CAN_CHANGE_THE_PRICE_TO_LESS_PURCHASES { get; set; }
        public Nullable<bool> CAN_CHANGE_STORES { get; set; }
        public Nullable<short> COM_STORE_ID { get; set; }
        public Nullable<bool> Can_See_The_ACC_BALANCE { get; set; }
        public Nullable<bool> CAN_SEE_LAST_BUY_PRICE { get; set; }
        public Nullable<bool> DISABLE_BILL_PAY_TYPE { get; set; }
        public Nullable<bool> CAN_CHANGE_PAY_ACCOUNT { get; set; }
        public Nullable<int> ACC_PAY_ID { get; set; }
        public Nullable<byte> SELL_TYPE_ID { get; set; }
        public Nullable<bool> BILLS_ON_DEMAND { get; set; }
        public Nullable<bool> REPORTS_WITH_PRICE { get; set; }
        public Nullable<bool> SEE_HIS_BILL_STORES_ONLY { get; set; }
        public Nullable<short> EMP_ID { get; set; }
        public Nullable<bool> CAN_CHANGE_THE_PRICE_LESS_BUY { get; set; }
    }
}
