//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBOXACCOUNT
    {
        public int BOXACC_ID { get; set; }
        public string UID { get; set; }
        public int ACC_ID { get; set; }
        public int BOXACC_TYPE { get; set; }
    }
}
