//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBOX
    {
        public int BOX_ID { get; set; }
        public string BOX_CODE { get; set; }
        public string BOX_AR_NAME { get; set; }
        public string BOX_EN_NAME { get; set; }
        public Nullable<int> BOX_ACCOUNT_ID { get; set; }
        public string BOX_REMARKS { get; set; }
        public Nullable<bool> BOX_OR_BANK { get; set; }
    }
}
