//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCAR_STATUS
    {
        public int CAR_STATUS_ID { get; set; }
        public string CAR_STATUS_CODE { get; set; }
        public string CAR_STATUS_AR_NAME { get; set; }
        public string CAR_STATUS_EN_NAME { get; set; }
        public string CAR_STATUS_NOTES { get; set; }
        public Nullable<int> INSERT_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public Nullable<int> MODIFY_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
    }
}
