//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCLASS
    {
        public int CLASS_ID { get; set; }
        public int MARKA_ID { get; set; }
        public string CLASS_CODE { get; set; }
        public string CLASS_AR_NAME { get; set; }
        public string CLASS_EN_NAME { get; set; }
        public string CLASS_NUMBER { get; set; }
        public string CLASS_NOTES { get; set; }
        public Nullable<int> INSERT_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public Nullable<int> MODIFY_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
    }
}
