//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCOLOUR
    {
        public int COLOUR_ID { get; set; }
        public string COLOUR_CODE { get; set; }
        public string COLOUR_AR_NAME { get; set; }
        public string COLOUR_EN_NAME { get; set; }
        public double COLOUR_COLOUR { get; set; }
        public string COLOUR_NOTES { get; set; }
        public Nullable<int> INSERT_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public Nullable<int> MODIFY_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
    }
}
