//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEPHONE_CAT
    {
        public byte TELE_CAT_ID { get; set; }
        public string TELE_CAT_AR_NAME { get; set; }
        public string TELE_CAT_EN_NAME { get; set; }
    }
}
