//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXPINSI
    {
        public int EXPINSIS_ID { get; set; }
        public string EXPINSIS_CODE { get; set; }
        public string EXPINSIS_AR_NAME { get; set; }
        public string EXPINSIS_EN_NAME { get; set; }
        public Nullable<int> EXPINSIS_ACCOUNT_ID { get; set; }
        public string EXPINSIS_REMARKS { get; set; }
    }
}
