//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFOLLLOW_PRODUCTION_DETAILS
    {
        public int FOLLOW_PRODCUCTION_DETAILS_ID { get; set; }
        public int FOLLOW_PRODUCTION_ID { get; set; }
        public string FOLLOW_PRODUCTION_CUSTOMER { get; set; }
        public string FOLLOW_PRODUCTION_ORDER { get; set; }
        public string FOLLOW_PRODUCTION_MODEL_NO { get; set; }
        public string FOLLOW_PRODUCTION_TYPE { get; set; }
        public string FOLLOW_PRODUCTION_FABRIC_TYPE { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_MAIN_QUANTITY { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_CUT_QUANTITY { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_PATREON { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_CUT { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_PRODUCTION { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_FINISH { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_WASHING_STORE { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_WASHING { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_CANNING { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_READYMADE_STORE_A { get; set; }
        public Nullable<double> FOLLOW_PRODUCTION_READYMADE_STORE_B { get; set; }
        public string FOLLOW_PRODUCTION_NOTES { get; set; }
        public string FOLLOW_PRODUCTION_AVIRAGE { get; set; }
        public string FOLLOW_PRODUCTION_BE_SURE { get; set; }
    }
}
