//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFOLLOW_PRODUCTION
    {
        public int FOLLOW_PRODUCTION_ID { get; set; }
        public string FOLLOW_PRODUCTION_CODE { get; set; }
        public System.DateTime FOLLOW_PRODUCTION_DATE { get; set; }
        public string FOLLOW_PRODUCTION_NOTES { get; set; }
    }
}
