//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public int Theme_ID { get; set; }
        public string Theme_Name { get; set; }
        public Nullable<long> TitleBackColor { get; set; }
        public Nullable<long> TitleForeColor { get; set; }
        public Nullable<long> BackColor1 { get; set; }
        public Nullable<long> BackColor2 { get; set; }
        public Nullable<long> ForeColor { get; set; }
        public Nullable<long> MenuColor { get; set; }
        public Nullable<long> menuButtonsColor { get; set; }
        public Nullable<long> menuButtonsSelectedColor { get; set; }
        public Nullable<long> menuButtonsHoverColor { get; set; }
        public Nullable<long> menuButtonsForeColor { get; set; }
        public Nullable<long> XpandoHeaderColor { get; set; }
        public Nullable<long> XpandoColor { get; set; }
        public Nullable<long> XpandoButtonsColor { get; set; }
        public string BackGroundPath { get; set; }
    }
}
