//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAY_TYPES
    {
        public int PAY_TYPE_ID { get; set; }
        public string PAY_TYPE_CODE { get; set; }
        public string PAY_TYPE_AR_NAME { get; set; }
        public string PAY_TYPE_EN_NAME { get; set; }
        public string PAY_TYPE_NOTES { get; set; }
    }
}
