//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRECENTADDEDBILL
    {
        public int FRECENTADDEDBILLID { get; set; }
        public string FRECENTADDEDBILLCODE { get; set; }
        public string FRECENTADDEDBILLTYPE { get; set; }
        public System.DateTime FRECENTADDEDBILLDATE { get; set; }
        public int FRECENTADDEDBILLSTORE { get; set; }
        public string FRECENTADDEDBILLNOTE { get; set; }
        public Nullable<System.DateTime> FRECENTADDEDBILLDATEOFNOTIFICATION { get; set; }
        public bool FRECENTADDEDBILLNOTIFIED { get; set; }
    }
}
