//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRECENTMINQTY
    {
        public int FRECENTMINQTYID { get; set; }
        public string FRECENTMINQTYCODE { get; set; }
        public System.DateTime FRECENTMINQTYDATE { get; set; }
        public int FRECENTMINQTYSTORE { get; set; }
        public string FRECENTMINQTYNOTE { get; set; }
        public Nullable<System.DateTime> FRECENTMINQTYDATEOFNOTIFICATION { get; set; }
        public bool FRECENTMINQTYNOTIFIED { get; set; }
    }
}
