//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UID
    {
        public string UID1 { get; set; }
        public string UPWD { get; set; }
        public Nullable<bool> SavePWD { get; set; }
        public Nullable<double> SHIFT_NUMBER { get; set; }
        public string USER_LETTER { get; set; }
        public int USER_TYPE { get; set; }
        public string TOKEN { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public int Id { get; set; }
    }
}
