//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsrPrevileg
    {
        public string UID { get; set; }
        public string MenuArName { get; set; }
        public string MenuEnName { get; set; }
        public string FormName { get; set; }
        public Nullable<bool> MenuOpen { get; set; }
        public Nullable<bool> OpAdd { get; set; }
        public Nullable<bool> OpUpdate { get; set; }
        public Nullable<bool> OpDelete { get; set; }
        public Nullable<bool> OpPreview { get; set; }
        public Nullable<bool> OpPrint { get; set; }
        public Nullable<bool> OpSearch { get; set; }
        public Nullable<int> Id { get; set; }
        public string Token { get; set; }
    
        public virtual UsrPrevileg UsrPrevilegs1 { get; set; }
        public virtual UsrPrevileg UsrPrevileg1 { get; set; }
        public virtual UsrPrevileg UsrPrevilegs11 { get; set; }
        public virtual UsrPrevileg UsrPrevileg2 { get; set; }
    }
}
