//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NOTIFICATIONS
    {
        public string EMP_AR_NAME { get; set; }
        public string EMP_EN_NAME { get; set; }
        public string ENTRY_NUMBER { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string CHECK_NUMBER { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string ENTRY_REMARKS { get; set; }
        public string ENTRY_SETTING_AR_NAME { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_AR_NAME { get; set; }
        public string ACC_EN_NAME { get; set; }
        public Nullable<bool> PAIED { get; set; }
        public string ACC_CODE_DETAILS { get; set; }
        public string ACC_AR_NAME_DETAILS { get; set; }
        public Nullable<short> ENTRY_ROW_NUMBER { get; set; }
        public Nullable<long> ENTRY_ID { get; set; }
        public Nullable<double> ENTRY_CREDIT { get; set; }
        public Nullable<double> ENTRY_DEBIT { get; set; }
        public string ACC_EN_NAME_DETAILS { get; set; }
        public string EMP_CODE { get; set; }
        public string ACC_CUSTOMER_CODE { get; set; }
        public string ENTRY_DETAILS_REMARKS { get; set; }
    }
}
